

export function get() {
  return {
    "products": [
      {
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "3.5",
        "normalPrice": "3.5",
        "nutritionalInfo": null,
        "id": 578327,
        "title": "Fresh Carrots",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01025611_big01025611-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01025611_big01025611-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "500 g",
        "status": "status_available",
        "imageUrlBasename": "big_big01025611_big01025611-1.jpg",
        "currency": "MYR",
        "productBrand": "First Pick",
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 637959,
        "title": "Fresh Milk",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01057713_big01057713-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01057713_big01057713-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "2 x 1 l",
        "status": "status_available",
        "imageUrlBasename": "big_big01057713_big01057713-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "18.75",
        "normalPrice": "18.75",
        "nutritionalInfo": null,
        "productBrand": "Farmhouse",
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 637950,
        "title": "Avocado (Australia)",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big12114_big12114-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big12114_big12114-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "each",
        "status": "status_available",
        "imageUrlBasename": "big_big12114_big12114-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "6.9",
        "normalPrice": "6.9",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 710197,
        "title": "Broccoli - Australia",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big12415_big12415-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big12415_big12415-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "350.0",
        "size": "350 g",
        "status": "status_available",
        "imageUrlBasename": "big_big12415_big12415-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "10.15",
        "normalPrice": "10.15",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 577799,
        "title": "Blueberry",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01028722_big01028722-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01028722_big01028722-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "125 g",
        "status": "status_available",
        "imageUrlBasename": "big_big01028722_big01028722-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "13.9",
        "normalPrice": "13.9",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 582601,
        "title": "Potato - Holland",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01023056_big01023056-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01023056_big01023056-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "500 g",
        "status": "status_available",
        "imageUrlBasename": "big_big01023056_big01023056-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "2.5",
        "normalPrice": "2.5",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 623035,
        "title": "Chicken Tenderloin",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big14352_big14352-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big14352_big14352-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "300.0",
        "size": "300 g",
        "status": "status_available",
        "imageUrlBasename": "big_big14352_big14352-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "6.87",
        "normalPrice": "6.87",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 578899,
        "title": "Onion - Yellow",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01023064_big01023064-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01023064_big01023064-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "500 g",
        "status": "status_available",
        "imageUrlBasename": "big_big01023064_big01023064-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "3.5",
        "normalPrice": "3.5",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 637821,
        "title": "Salmon Fish Fillet",
        "description": "Fresh stock only available after 12pm daily",
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big1810005201_big1810005201-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big1810005201_big1810005201-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "300.0",
        "size": "300 g",
        "status": "status_available",
        "imageUrlBasename": "big_big1810005201_big1810005201-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "29.4",
        "normalPrice": "29.4",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 621846,
        "title": "Capsicum - Red",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big10409_big10409-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big10409_big10409-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "150.0",
        "size": "150 g",
        "status": "status_available",
        "imageUrlBasename": "big_big10409_big10409-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "2.99",
        "normalPrice": "2.99",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 622335,
        "title": "Red Watermelon",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big10281_big10281-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big10281_big10281-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "1000.0",
        "size": "1 kg",
        "status": "status_available",
        "imageUrlBasename": "big_big10281_big10281-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "3.6",
        "normalPrice": "3.6",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 621668,
        "title": "Banana Berangan",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big10288_big10288-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big10288_big10288-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "950.0",
        "size": "950 g",
        "status": "status_available",
        "imageUrlBasename": "big_big10288_big10288-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "6.37",
        "normalPrice": "6.37",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 621042,
        "title": "Cameron Tomato",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big12194_big12194-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big12194_big12194-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "240.0",
        "size": "240 g",
        "status": "status_available",
        "imageUrlBasename": "big_big12194_big12194-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "0.98",
        "normalPrice": "0.98",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 637949,
        "title": "Banana Cavendish",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big11743_big11743-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big11743_big11743-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "1000.0",
        "size": "1 kg",
        "status": "status_available",
        "imageUrlBasename": "big_big11743_big11743-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "6.8",
        "normalPrice": "6.8",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 581873,
        "title": "Cherry Honey Tomato",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01040957_big01040957-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01040957_big01040957-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "275 g",
        "status": "status_available",
        "imageUrlBasename": "big_big01040957_big01040957-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "5.25",
        "normalPrice": "5.25",
        "nutritionalInfo": null,
        "productBrand": "Genting Garden",
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 637954,
        "title": "Mineral Water",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01009698_big01009698-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01009698_big01009698-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "6 l",
        "status": "status_available",
        "imageUrlBasename": "big_big01009698_big01009698-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "10.2",
        "normalPrice": "10.2",
        "nutritionalInfo": null,
        "productBrand": "Spritzer",
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 622390,
        "title": "Cameron Tomato On Truss",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big14781_big14781-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big14781_big14781-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_grams",
        "soldBy": "sold_by_weight",
        "amountPerUnit": "800.0",
        "size": "800 g",
        "status": "status_available",
        "imageUrlBasename": "big_big14781_big14781-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "9.2",
        "normalPrice": "9.2",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 581654,
        "title": "Onion - Red",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01023050_big01023050-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01023050_big01023050-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "500 g",
        "status": "status_available",
        "imageUrlBasename": "big_big01023050_big01023050-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "2.5",
        "normalPrice": "2.5",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 582552,
        "title": "Turkey Lemon",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01037333_big01037333-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01037333_big01037333-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "5 pcs",
        "status": "status_available",
        "imageUrlBasename": "big_big01037333_big01037333-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "14.9",
        "normalPrice": "14.9",
        "nutritionalInfo": null,
        "productBrand": null,
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      },
      {
        "id": 637214,
        "title": "Wholemeal",
        "description": null,
        "imageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01029566_big01029566-1.jpg",
        "previewImageUrl": "https://honestbees.s3.amazonaws.com/products/images/480/big_big01029566_big01029566-1.jpg",
        "slug": null,
        "barcode": null,
        "unitType": "unit_type_item",
        "soldBy": "sold_by_item",
        "amountPerUnit": "1.0",
        "size": "400 g",
        "status": "status_available",
        "imageUrlBasename": "big_big01029566_big01029566-1.jpg",
        "currency": "MYR",
        "promotionStartsAt": null,
        "promotionEndsAt": null,
        "price": "3.2",
        "normalPrice": "3.2",
        "nutritionalInfo": null,
        "productBrand": "Gardenia",
        "productInfo": null,
        "packingSize": null,
        "descriptionHtml": null,
        "countryOfOrigin": null,
        "tags": [],
        "alcohol": false
      }
    ],
      "meta": {
      "current_page": 1,
        "total_pages": 879,
          "total_count": 17571
    }
  }
}